/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;

public class AdvocatePatchFormBuilder {
    //the instance to build
    private AdvocatePatchForm advocatePatchForm;

    /**
     * Default constructor to initialize the instance
     */
    public AdvocatePatchFormBuilder() {
        advocatePatchForm = new AdvocatePatchForm();
    }

    /**
     * The advocate's name
     */
    public AdvocatePatchFormBuilder name(String name) {
        advocatePatchForm.setName(name);
        return this;
    }

    /**
     * The advocate's last name
     */
    public AdvocatePatchFormBuilder lastname(String lastname) {
        advocatePatchForm.setLastname(lastname);
        return this;
    }

    /**
     * The advocate's email
     */
    public AdvocatePatchFormBuilder email(String email) {
        advocatePatchForm.setEmail(email);
        return this;
    }

    public AdvocatePatchFormBuilder payoutThreshold(Integer payoutThreshold) {
        advocatePatchForm.setPayoutThreshold(payoutThreshold);
        return this;
    }

    /**
     * The total amount of bonuses that the advocate must generate before being able to create a bonus redemption request.
     */
    public AdvocatePatchFormBuilder claimedBalance(Integer claimedBalance) {
        advocatePatchForm.setClaimedBalance(claimedBalance);
        return this;
    }

    /**
     * The unclaimed balance
     */
    public AdvocatePatchFormBuilder unclaimedBalance(Integer unclaimedBalance) {
        advocatePatchForm.setUnclaimedBalance(unclaimedBalance);
        return this;
    }

    /**
     * The currency code
     */
    public AdvocatePatchFormBuilder currencyCode(String currencyCode) {
        advocatePatchForm.setCurrencyCode(currencyCode);
        return this;
    }

    /**
     * The advocate's avatar URL
     */
    public AdvocatePatchFormBuilder avatarUrl(String avatarUrl) {
        advocatePatchForm.setAvatarUrl(avatarUrl);
        return this;
    }

    /**
     * Useful to store extra information about the advocate. e.g, the phone number, address, etc.
     */
    public AdvocatePatchFormBuilder metadata(String metadata) {
        advocatePatchForm.setMetadata(metadata);
        return this;
    }

    /**
     * Whether or not the advocate is allowed to refer services/products (Useful when using the Full Widget template).
     */
    public AdvocatePatchFormBuilder canRefer(Boolean canRefer) {
        advocatePatchForm.setCanRefer(canRefer);
        return this;
    }

    /**
     * The advocate's token
     */
    public AdvocatePatchFormBuilder token(String token) {
        advocatePatchForm.setToken(token);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AdvocatePatchForm build() {
        return advocatePatchForm;
    }
}