/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;

public class AdvocateBuilder {
    //the instance to build
    private Advocate advocate;

    /**
     * Default constructor to initialize the instance
     */
    public AdvocateBuilder() {
        advocate = new Advocate();
    }

    /**
     * The advocate's name
     */
    public AdvocateBuilder name(String name) {
        advocate.setName(name);
        return this;
    }

    /**
     * The advocate's last name
     */
    public AdvocateBuilder lastname(String lastname) {
        advocate.setLastname(lastname);
        return this;
    }

    /**
     * The advocate's email
     */
    public AdvocateBuilder email(String email) {
        advocate.setEmail(email);
        return this;
    }

    /**
     * The total amount of bonuses that the advocate must generate before being able to create a bonus redemption request.
     */
    public AdvocateBuilder payoutThreshold(int payoutThreshold) {
        advocate.setPayoutThreshold(payoutThreshold);
        return this;
    }

    /**
     * The advocate's avatar URL
     */
    public AdvocateBuilder avatarUrl(String avatarUrl) {
        advocate.setAvatarUrl(avatarUrl);
        return this;
    }

    /**
     * Useful to store extra information about the advocate. e.g, the phone number, address, etc.
     */
    public AdvocateBuilder metadata(String metadata) {
        advocate.setMetadata(metadata);
        return this;
    }

    /**
     * Whether or not the advocate is allowed to refer services/products (Useful when using the Full Widget template).
     */
    public AdvocateBuilder canRefer(Boolean canRefer) {
        advocate.setCanRefer(canRefer);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Advocate build() {
        return advocate;
    }
}