/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;

public class BonusesForm1Builder {
    //the instance to build
    private BonusesForm1 bonusesForm1;

    /**
     * Default constructor to initialize the instance
     */
    public BonusesForm1Builder() {
        bonusesForm1 = new BonusesForm1();
    }

    /**
     * The bonuses' wrapper
     */
    public BonusesForm1Builder bonus(Bonuses1 bonus) {
        bonusesForm1.setBonus(bonus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BonusesForm1 build() {
        return bonusesForm1;
    }
}