/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;

public class BonusesFormBuilder {
    //the instance to build
    private BonusesForm bonusesForm;

    /**
     * Default constructor to initialize the instance
     */
    public BonusesFormBuilder() {
        bonusesForm = new BonusesForm();
    }

    /**
     * The bonuses' wrapper
     */
    public BonusesFormBuilder bonus(Bonuses bonus) {
        bonusesForm.setBonus(bonus);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BonusesForm build() {
        return bonusesForm;
    }
}