/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Bonuses1 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5083463822840076333L;
    private String advocateToken;
    private String reference;
    private int bonusAmount;
    /** GETTER
     * The referral's token.
     */
    @JsonGetter("advocate_token")
    public String getAdvocateToken ( ) { 
        return this.advocateToken;
    }
    
    /** SETTER
     * The referral's token.
     */
    @JsonSetter("advocate_token")
    public void setAdvocateToken (String value) { 
        this.advocateToken = value;
    }
 
    /** GETTER
     * The reference number for this request. Usually the order_id, payment_id, or timestamp.
     */
    @JsonGetter("reference")
    public String getReference ( ) { 
        return this.reference;
    }
    
    /** SETTER
     * The reference number for this request. Usually the order_id, payment_id, or timestamp.
     */
    @JsonSetter("reference")
    public void setReference (String value) { 
        this.reference = value;
    }
 
    /** GETTER
     * The bonus amount to give to the advocate.
     */
    @JsonGetter("bonus_amount")
    public int getBonusAmount ( ) { 
        return this.bonusAmount;
    }
    
    /** SETTER
     * The bonus amount to give to the advocate.
     */
    @JsonSetter("bonus_amount")
    public void setBonusAmount (int value) { 
        this.bonusAmount = value;
    }
 
}
 