/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Bonuses 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5535551959060338263L;
    private String advocateToken;
    private String reference;
    private Double paymentAmount;
    /** GETTER
     * The referral's token. Usually the one that completed the purchase, or trigger an event.
     */
    @JsonGetter("advocate_token")
    public String getAdvocateToken ( ) { 
        return this.advocateToken;
    }
    
    /** SETTER
     * The referral's token. Usually the one that completed the purchase, or trigger an event.
     */
    @JsonSetter("advocate_token")
    public void setAdvocateToken (String value) { 
        this.advocateToken = value;
    }
 
    /** GETTER
     * The reference number for this request. Usually the order_id, payment_id, or timestamp.
     */
    @JsonGetter("reference")
    public String getReference ( ) { 
        return this.reference;
    }
    
    /** SETTER
     * The reference number for this request. Usually the order_id, payment_id, or timestamp.
     */
    @JsonSetter("reference")
    public void setReference (String value) { 
        this.reference = value;
    }
 
    /** GETTER
     * The payment amount the referrals has made. Required for a percentage based campaign.
     */
    @JsonGetter("payment_amount")
    public Double getPaymentAmount ( ) { 
        return this.paymentAmount;
    }
    
    /** SETTER
     * The payment amount the referrals has made. Required for a percentage based campaign.
     */
    @JsonSetter("payment_amount")
    public void setPaymentAmount (Double value) { 
        this.paymentAmount = value;
    }
 
}
 