/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;

public class ForceBonusesBuilder {
    //the instance to build
    private ForceBonuses forceBonuses;

    /**
     * Default constructor to initialize the instance
     */
    public ForceBonusesBuilder() {
        forceBonuses = new ForceBonuses();
    }

    /**
     * The referral's token.
     */
    public ForceBonusesBuilder advocateToken(String advocateToken) {
        forceBonuses.setAdvocateToken(advocateToken);
        return this;
    }

    /**
     * The reference number for this request. Usually the order_id, payment_id, or timestamp.
     */
    public ForceBonusesBuilder reference(String reference) {
        forceBonuses.setReference(reference);
        return this;
    }

    /**
     * The bonus amount to give to the advocate.
     */
    public ForceBonusesBuilder bonusAmount(int bonusAmount) {
        forceBonuses.setBonusAmount(bonusAmount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ForceBonuses build() {
        return forceBonuses;
    }
}