/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;

public class RedemptionRequestBuilder {
    //the instance to build
    private RedemptionRequest redemptionRequest;

    /**
     * Default constructor to initialize the instance
     */
    public RedemptionRequestBuilder() {
        redemptionRequest = new RedemptionRequest();
    }

    /**
     * The advocate's token
     */
    public RedemptionRequestBuilder advocateToken(String advocateToken) {
        redemptionRequest.setAdvocateToken(advocateToken);
        return this;
    }

    /**
     * The request status identifier
     */
    public RedemptionRequestBuilder requestStatusSlug(String requestStatusSlug) {
        redemptionRequest.setRequestStatusSlug(requestStatusSlug);
        return this;
    }

    /**
     * The request action identifier
     */
    public RedemptionRequestBuilder requestActionSlug(String requestActionSlug) {
        redemptionRequest.setRequestActionSlug(requestActionSlug);
        return this;
    }

    /**
     * The currency code
     */
    public RedemptionRequestBuilder currencyCode(String currencyCode) {
        redemptionRequest.setCurrencyCode(currencyCode);
        return this;
    }

    /**
     * The amount to be redeemed
     */
    public RedemptionRequestBuilder amount(int amount) {
        redemptionRequest.setAmount(amount);
        return this;
    }

    /**
     * The description of the requests, useful to store extra information about the request.
     */
    public RedemptionRequestBuilder description(String description) {
        redemptionRequest.setDescription(description);
        return this;
    }

    /**
     * The advocate's PayPal username
     */
    public RedemptionRequestBuilder advocatesPaypalUsername(String advocatesPaypalUsername) {
        redemptionRequest.setAdvocatesPaypalUsername(advocatesPaypalUsername);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RedemptionRequest build() {
        return redemptionRequest;
    }
}