/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;

public class ReferralFormBuilder {
    //the instance to build
    private ReferralForm referralForm;

    /**
     * Default constructor to initialize the instance
     */
    public ReferralFormBuilder() {
        referralForm = new ReferralForm();
    }

    /**
     * The referral's wrapper
     */
    public ReferralFormBuilder referral(Referral referral) {
        referralForm.setReferral(referral);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ReferralForm build() {
        return referralForm;
    }
}