/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ReferralForm 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4840971067085822662L;
    private Referral referral;
    /** GETTER
     * The referral's wrapper
     */
    @JsonGetter("referral")
    public Referral getReferral ( ) { 
        return this.referral;
    }
    
    /** SETTER
     * The referral's wrapper
     */
    @JsonSetter("referral")
    public void setReferral (Referral value) { 
        this.referral = value;
    }
 
}
 