/*
 * GeniusReferralsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.geniusreferrals.api;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.geniusreferrals.com";

    //The content type
    //TODO: Replace the contentType with an appropriate value
    public static String contentType = "application/json";

    //Your API Token, you can get your token here https://www.geniusreferrals.com/en/settings/api-access
    //TODO: Replace the xAuthToken with an appropriate value
    public static String xAuthToken = "3b9d11374b602fb47b987dff90f1c5940a1f377f";

}
